---
title: "plot4blogdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(pipeR)
library(DT)
library(data.table)
library(DiagrammeR)
library(knitr)
library(rmarkdown)
library(blogdown)
library(formattable)
```

```{r insulin treatment 1}
timing <- c("朝食前", "昼食前", "夕食前", "眠前")
tibble(
      time = factor(rep(timing, 2), levels = timing),
      BS = c(100, 100, 100, 140, 100, 180, 160, 160),
      status = c(rep("ideal", 4), rep("actual", 4))
      ) -> tbl1
tibble(
      time=factor(c(rep("昼食前",2),rep("夕食前",2), rep("眠前",2)), levels = timing),
      BS=c(180,100,160,180,160,200),
      group=c(1,1,2,2,3,3)
    ) -> tbl2
tibble(
      time=factor(c("昼食前",rep("夕食前",2),"眠前"), levels = timing),
      BS=c(180,180,160,200),
      group=c(1,1,2,2)
    ) -> tbl3

ggplot(
    data=tbl1,
    aes(x = time, y = BS, color = status, group=status)) +
    geom_line() +
    geom_path(data=tbl2,
      aes(x=time, y=BS, group=group), 
      arrow=arrow() ,lineend = "round", color = "black") +
    geom_line(data=tbl3,
      aes(x=time, y=BS, group=group),
      color="blue", linetype="dashed") +
    coord_fixed(ratio=0.01)

```